# Generated by Django 5.1.6 on 2025-03-05 11:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cover', models.ImageField(upload_to='Albums/covers/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True, verbose_name=3000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('artist_s', models.ManyToManyField(related_name='albums', to='artists.artist')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cover', models.ImageField(upload_to='Playlists/covers/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True, verbose_name=3000)),
                ('playlist_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
            },
        ),
        migrations.CreateModel(
            name='PlaylistCollaborators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborated_playlists', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_collaborators', to='songs.playlist')),
            ],
            options={
                'verbose_name': 'Playlist collaborator',
                'verbose_name_plural': 'Playlist collaborators',
                'unique_together': {('playlist', 'collaborator')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='collaborators',
            field=models.ManyToManyField(through='songs.PlaylistCollaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cover', models.ImageField(upload_to='Songs/covers/%Y/%m/%d/')),
                ('name', models.CharField(max_length=500)),
                ('song', models.FileField(upload_to='Songs/covers/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['wav', 'flac'])])),
                ('duration', models.DurationField(help_text='Enter Duration in seconds.')),
                ('credits', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='songs.album')),
                ('artist_s', models.ManyToManyField(related_name='songs', to='artists.artist')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.CreateModel(
            name='PlaylistSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='songs.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
            options={
                'verbose_name': 'Playlist song',
                'verbose_name_plural': 'Playlist songs',
                'unique_together': {('playlist', 'song')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(through='songs.PlaylistSongs', to='songs.song'),
        ),
    ]
