# Generated by Django 5.1.6 on 2025-03-05 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Liked Songs', editable=False, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like_playlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liked song',
                'verbose_name_plural': 'Liked songs',
            },
        ),
        migrations.CreateModel(
            name='UserLikedSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('like_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_songs', to='songs.likedplaylist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
            options={
                'verbose_name': 'User Liked song',
                'verbose_name_plural': 'User Liked songs',
                'unique_together': {('like_playlist', 'song')},
            },
        ),
        migrations.AddField(
            model_name='likedplaylist',
            name='songs',
            field=models.ManyToManyField(related_name='likes', through='songs.UserLikedSongs', to='songs.song'),
        ),
    ]
