# Generated by Django 5.1.6 on 2025-03-31 08:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_likedplaylist_userlikedsongs_likedplaylist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistsongs',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='songs.song'),
        ),
        migrations.CreateModel(
            name='PlaylistCollaboratorToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='cZAVcRvickGX2Khv_-rHlA', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 3, 31, 8, 29, 7, 952698, tzinfo=datetime.timezone.utc), editable=False)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_collaborator_tokens', to='songs.playlist')),
            ],
            options={
                'verbose_name': 'Playlist collaborator token',
                'verbose_name_plural': 'Playlist collaborator tokens',
            },
        ),
    ]
