# Generated by Django 5.1.6 on 2025-03-31 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_playlistsongs_song_playlistcollaboratortoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistcollaboratortoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 8, 46, 3, 953199, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='playlistcollaboratortoken',
            name='token',
            field=models.CharField(default='Heyn8Wxl62F2S-H5BhXUnQ', max_length=50, unique=True),
        ),
    ]
