# Generated by Django 5.1.6 on 2025-03-31 10:15

import datetime
import songs.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_alter_playlistcollaboratortoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistcollaboratortoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 10, 20, 35, 77494, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='playlistcollaboratortoken',
            name='token',
            field=models.CharField(default=songs.utils.generate_playlist_collaborator_token, max_length=50, unique=True),
        ),
    ]
