# Generated by Django 5.1.6 on 2025-04-03 13:43

import songs.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_playlistcollaboratortoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistcollaboratortoken',
            name='expires_at',
            field=models.DateTimeField(default=songs.utils.five_minutes),
        ),
    ]
