# Generated by Django 5.1.6 on 2025-03-06 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0002_likedplaylist_userlikedsongs_likedplaylist_songs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(choices=[('Updated cover', 'updated cover'), ('Updated name', 'updated name'), ('Updated description', 'updated description')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='songs.album')),
            ],
            options={
                'verbose_name': 'Album Log',
                'verbose_name_plural': 'Album Logs',
            },
        ),
        migrations.CreateModel(
            name='PlaylistLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(choices=[('Updated cover', 'updated cover'), ('Updated name', 'updated name'), ('Updated description', 'updated description'), ('Updated playlist type', 'updated playlist type')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='songs.playlist')),
            ],
            options={
                'verbose_name': 'Playlist Log',
                'verbose_name_plural': 'Playlist Logs',
            },
        ),
        migrations.CreateModel(
            name='StreamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('streamed_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='songs.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stream Log',
                'verbose_name_plural': 'Stream Logs',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(choices=[('Updated nickname', 'updated nickname'), ('Updated email', 'updated email'), ('Updated gender', 'updated gender'), ('Updated birthdate', 'updated birthdate'), ('Updated country', 'updated country'), ('Updated avatar', 'updated avatar'), ('Upgraded to admin', 'upgraded to admin'), ('Deleted', 'deleted')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Log',
                'verbose_name_plural': 'User Logs',
            },
        ),
    ]
